# Generated by Django 3.1.2 on 2020-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(max_length=15, verbose_name='Сложность'),
        ),
    ]
