# Generated by Django 3.1.2 on 2020-10-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201021_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=15, verbose_name='Время выполнения'),
        ),
    ]
