# Generated by Django 3.1.2 on 2020-10-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201021_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=20, verbose_name='Имя')),
                ('Forename', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('evulation_work', models.CharField(max_length=20, verbose_name='Качество работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
