# Generated by Django 3.1.3 on 2021-01-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_human'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='task',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.CharField(default=1, max_length=15, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=1, max_length=15, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='id_person',
            field=models.CharField(default=1, max_length=2, verbose_name='Выполнитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='id_status',
            field=models.TextField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
