# Generated by Django 3.1.2 on 2020-10-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_human'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
