# Generated by Django 3.1.3 on 2021-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210103_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.CharField(max_length=15, verbose_name='Описание')),
                ('date', models.CharField(max_length=15, verbose_name='Дата')),
                ('id_person', models.CharField(max_length=2, verbose_name='Выполнитель')),
                ('id_status', models.TextField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
