# Generated by Django 3.1.2 on 2020-11-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201026_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
