# Generated by Django 3.1.3 on 2021-01-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='age',
            new_name='ages',
        ),
    ]
