# Generated by Django 3.1.3 on 2020-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201128_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='difficulty',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='num_people',
            new_name='id_person',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='id_status',
            field=models.CharField(default=1, max_length=2, verbose_name='Количество людей'),
            preserve_default=False,
        ),
    ]
