# Generated by Django 3.1.3 on 2021-01-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210103_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='task1',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата'),
        ),
    ]
