# Generated by Django 3.1.3 on 2020-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201128_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=15, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_person',
            field=models.CharField(max_length=2, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_status',
            field=models.CharField(max_length=2, verbose_name='Статус'),
        ),
    ]
