# Generated by Django 3.1.3 on 2021-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210103_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task1',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='task1',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task1',
            name='id_status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
    ]
