# Generated by Django 3.1.3 on 2020-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201128_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=45, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_person',
            field=models.CharField(max_length=20, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
    ]
