# Generated by Django 3.1.3 on 2021-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='description',
            field=models.TextField(max_length=40, verbose_name='Описание'),
        ),
    ]
