# Generated by Django 3.1.3 on 2021-01-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='id_status',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=300),
        ),
    ]
