# Generated by Django 3.1.2 on 2021-01-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210104_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='id_performing_person',
            field=models.CharField(max_length=20, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task1',
            name='id_status',
            field=models.CharField(max_length=300),
        ),
    ]
