# Generated by Django 3.1.3 on 2021-01-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210104_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='id_status',
            field=models.CharField(max_length=300, verbose_name='Статус'),
        ),
    ]
