# Generated by Django 3.1.3 on 2021-01-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210105_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='Forename',
        ),
        migrations.RemoveField(
            model_name='human',
            name='Surname',
        ),
        migrations.RemoveField(
            model_name='human',
            name='ages',
        ),
        migrations.RemoveField(
            model_name='human',
            name='evulation_work',
        ),
        migrations.AddField(
            model_name='human',
            name='first_name',
            field=models.CharField(default=1, max_length=10, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='id_branch',
            field=models.CharField(default=1, max_length=10, verbose_name='отдел разработки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='id_registarion',
            field=models.CharField(default=1, max_length=5, verbose_name='id при регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='second_name',
            field=models.CharField(default=1, max_length=15, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
