# Generated by Django 3.1.2 on 2021-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
