# Generated by Django 3.1.3 on 2021-01-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210107_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
