# Generated by Django 3.1.3 on 2021-01-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='id_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch'),
        ),
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
