# Generated by Django 3.1.3 on 2021-01-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210111_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='id_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task1',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status'),
        ),
    ]
