# Generated by Django 3.1.2 on 2021-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210116_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
